#!/bin/bash
#
# API Map - Docker Installation Script
# Usage: curl -fsSL https://raw.githubusercontent.com/qades/apimap/main/scripts/install.sh | bash
#
# This script installs API Map using Docker with proper directory setup.
# For binary installation (without Docker), see install-binary.sh
#
# Environment variables:
#   APIMAN_INSTALL_DIR    - Installation directory (default: ~/.local/share/apimap)
#   APIMAN_API_PORT       - API server port (default: 3000)
#   APIMAN_GUI_PORT       - GUI server port (default: 3001)
#   APIMAN_EXTERNAL_PORT  - External API port for port mapping (default: same as API_PORT)
#   APIMAN_EXTERNAL_GUI_PORT - External GUI port for port mapping (default: same as GUI_PORT)
#   APIMAN_SKIP_SYSTEMD   - Skip systemd service setup
#
# Port Mapping Example:
#   APIMAN_API_PORT=8080 APIMAN_EXTERNAL_PORT=8080 ./install.sh
#   This maps external port 8080 to internal port 3000
#

set -e

# Configuration
REPO="qades/apimap"
IMAGE="ghcr.io/qades/apimap:latest"
INSTALL_DIR="${APIMAN_INSTALL_DIR:-$HOME/.local/share/apimap}"
CONFIG_DIR="$INSTALL_DIR/config"
LOGS_DIR="$INSTALL_DIR/logs"
API_PORT="${APIMAN_API_PORT:-3000}"
GUI_PORT="${APIMAN_GUI_PORT:-3001}"
EXTERNAL_PORT="${APIMAN_EXTERNAL_PORT:-$API_PORT}"
EXTERNAL_GUI_PORT="${APIMAN_EXTERNAL_GUI_PORT:-$GUI_PORT}"
SERVICE_NAME="apimap"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Detect OS
detect_os() {
    case "$(uname -s)" in
        Linux*)     OS=Linux;;
        Darwin*)    OS=Mac;;
        CYGWIN*|MINGW*|MSYS*) OS=Windows;;
        *)          OS="UNKNOWN";;
    esac
    echo "$OS"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command_exists docker; then
        log_error "Docker is not installed."
        echo ""
        echo "Please install Docker first:"
        echo "  - Linux: https://docs.docker.com/engine/install/"
        echo "  - macOS: https://docs.docker.com/desktop/install/mac-install/"
        echo "  - Windows: https://docs.docker.com/desktop/install/windows-install/"
        exit 1
    fi
    
    # Check if docker daemon is running
    if ! docker info >/dev/null 2>&1; then
        log_error "Docker daemon is not running or not accessible."
        echo ""
        echo "Please start Docker and try again."
        exit 1
    fi
    
    log_success "Docker is installed and running"
}

# Create directories with proper permissions
setup_directories() {
    log_info "Setting up directories in $INSTALL_DIR..."
    
    mkdir -p "$CONFIG_DIR" "$LOGS_DIR"
    
    # Set ownership to UID 1001 (apimap user in container)
    if [ "$(detect_os)" = "Linux" ] || [ "$(detect_os)" = "Mac" ]; then
        # Try to set ownership to UID 1001
        if chown -R 1001:1001 "$CONFIG_DIR" "$LOGS_DIR" 2>/dev/null; then
            log_success "Directory ownership set to UID 1001"
        else
            log_warn "Could not change ownership to UID 1001 (may need sudo)"
            log_warn "Making directories world-writable as fallback..."
            chmod -R 777 "$CONFIG_DIR" "$LOGS_DIR"
        fi
    fi
    
    log_success "Directories created"
}

# Create default config if it doesn't exist
create_default_config() {
    local config_file="$CONFIG_DIR/config.yaml"
    
    if [ -f "$config_file" ]; then
        log_info "Existing configuration found at $config_file"
        return
    fi
    
    log_info "Creating default configuration..."
    
    cat > "$config_file" << 'EOF'
# API Map Configuration
# Generated by install script
# Documentation: https://github.com/qades/apimap#configuration

server:
  port: 3000
  host: "0.0.0.0"
  timeout: 120

logging:
  dir: "/app/logs"
  level: "info"
  maskKeys: true

# Configure your providers and API keys here
# providers:
#   openai:
#     apiKeyEnv: "OPENAI_API_KEY"
#     timeout: 180
#   
#   anthropic:
#     apiKeyEnv: "ANTHROPIC_API_KEY"
#     timeout: 180

# Configure routing rules here
# routes:
#   - pattern: "gpt-4*"
#     provider: openai
#     priority: 100

defaultProvider: null
EOF
    
    log_success "Default configuration created"
    log_info "Edit $config_file to add your API keys and routes"
}

# Create docker-compose.yml
create_compose_file() {
    log_info "Creating docker-compose.yml..."
    
    # Only add external port env vars if they differ from internal ports
    EXTERNAL_PORT_CONFIG=""
    if [ "${EXTERNAL_PORT}" != "${API_PORT}" ]; then
        EXTERNAL_PORT_CONFIG="      - EXTERNAL_PORT=${EXTERNAL_PORT}"
    fi
    if [ "${EXTERNAL_GUI_PORT}" != "${GUI_PORT}" ]; then
        EXTERNAL_PORT_CONFIG="${EXTERNAL_PORT_CONFIG}
      - EXTERNAL_GUI_PORT=${EXTERNAL_GUI_PORT}"
    fi
    
    cat > "$INSTALL_DIR/docker-compose.yml" << EOF
# API Map - Docker Compose Configuration

services:
  apimap:
    image: ${IMAGE}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped
    ports:
      - "${API_PORT}:3000"
      - "${GUI_PORT}:3001"
    environment:
      # API Keys - set these in your environment or config.yaml
      - OPENAI_API_KEY=\${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=\${GOOGLE_API_KEY:-}
      - GROQ_API_KEY=\${GROQ_API_KEY:-}
      - TOGETHER_API_KEY=\${TOGETHER_API_KEY:-}
      - FIREWORKS_API_KEY=\${FIREWORKS_API_KEY:-}
      - DEEPSEEK_API_KEY=\${DEEPSEEK_API_KEY:-}
      - MISTRAL_API_KEY=\${MISTRAL_API_KEY:-}
      - COHERE_API_KEY=\${COHERE_API_KEY:-}
      - OPENROUTER_API_KEY=\${OPENROUTER_API_KEY:-}
      - PERPLEXITY_API_KEY=\${PERPLEXITY_API_KEY:-}
      - ANYSCALE_API_KEY=\${ANYSCALE_API_KEY:-}
      
      # Ollama configuration (for local models)
      - OLLAMA_BASE_URL=\${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      
      # Port mapping configuration (for reverse proxy scenarios)
${EXTERNAL_PORT_CONFIG}
    volumes:
      - ${CONFIG_DIR}:/app/config:rw
      - ${LOGS_DIR}:/app/logs:rw
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
EOF
    
    log_success "docker-compose.yml created"
}

# Create wrapper script
create_wrapper_script() {
    log_info "Creating command wrappers..."
    
    # Create apimap command
    cat > "$INSTALL_DIR/apimap" << 'EOF'
#!/bin/bash
# API Map - Command wrapper

INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"

case "${1:-}" in
    start)
        echo "Starting API Map..."
        docker compose -f "$COMPOSE_FILE" up -d
        echo "API Map is running at:"
        echo "  API:  http://localhost:3000"
        echo "  GUI:  http://localhost:3001"
        ;;
    stop)
        echo "Stopping API Map..."
        docker compose -f "$COMPOSE_FILE" down
        ;;
    restart)
        echo "Restarting API Map..."
        docker compose -f "$COMPOSE_FILE" restart
        ;;
    logs)
        docker compose -f "$COMPOSE_FILE" logs -f
        ;;
    status)
        docker compose -f "$COMPOSE_FILE" ps
        ;;
    update)
        echo "Updating API Map..."
        docker compose -f "$COMPOSE_FILE" pull
        docker compose -f "$COMPOSE_FILE" up -d
        ;;
    config)
        ${EDITOR:-nano} "$INSTALL_DIR/config/config.yaml"
        ;;
    shell)
        docker compose -f "$COMPOSE_FILE" exec apimap sh
        ;;
    *)
        echo "API Map - Universal Model Router"
        echo ""
        echo "Usage: apimap [command]"
        echo ""
        echo "Commands:"
        echo "  start    Start API Map"
        echo "  stop     Stop API Map"
        echo "  restart  Restart API Map"
        echo "  logs     View logs"
        echo "  status   Check status"
        echo "  update   Update to latest version"
        echo "  config   Edit configuration"
        echo "  shell    Open shell in container"
        echo ""
        echo "Directories:"
        echo "  Config: $INSTALL_DIR/config"
        echo "  Logs:   $INSTALL_DIR/logs"
        ;;
esac
EOF
    
    chmod +x "$INSTALL_DIR/apimap"
    log_success "Wrapper script created"
}

# Setup systemd service (Linux only)
setup_systemd() {
    if [ -n "$APIMAN_SKIP_SYSTEMD" ]; then
        log_info "Skipping systemd setup (APIMAN_SKIP_SYSTEMD is set)"
        return
    fi
    
    if [ "$(detect_os)" != "Linux" ]; then
        log_info "Skipping systemd (not on Linux)"
        return
    fi
    
    if [ ! -d /etc/systemd/system ]; then
        log_info "Skipping systemd (not available)"
        return
    fi
    
    if [ "$EUID" -ne 0 ] && ! command_exists sudo; then
        log_warn "Cannot setup systemd without sudo access"
        return
    fi
    
    log_info "Setting up systemd service..."
    
    cat > /tmp/apimap.service << EOF
[Unit]
Description=API Map - Universal Model Router
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/apimap start
ExecStop=${INSTALL_DIR}/apimap stop

[Install]
WantedBy=multi-user.target
EOF
    
    if [ "$EUID" -eq 0 ]; then
        mv /tmp/apimap.service /etc/systemd/system/
    else
        sudo mv /tmp/apimap.service /etc/systemd/system/
    fi
    
    systemctl daemon-reload
    log_success "Systemd service installed"
    log_info "Enable with: sudo systemctl enable apimap"
    log_info "Start with:  sudo systemctl start apimap"
}

# Add to PATH suggestion
add_to_path_suggestion() {
    local shell_rc=""
    case "$SHELL" in
        */bash) shell_rc="$HOME/.bashrc" ;;
        */zsh)  shell_rc="$HOME/.zshrc" ;;
        */fish) shell_rc="$HOME/.config/fish/config.fish" ;;
    esac
    
    if [ -n "$shell_rc" ]; then
        echo ""
        log_info "To add 'apimap' to your PATH, run:"
        echo "  echo 'export PATH=\"$INSTALL_DIR:\$PATH\"' >> $shell_rc"
        echo "  source $shell_rc"
    fi
}

# Main installation
main() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║              API Map - Docker Installation                 ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    
    log_info "Installation directory: $INSTALL_DIR"
    log_info "API port: $API_PORT"
    log_info "GUI port: $GUI_PORT"
    if [ "${EXTERNAL_PORT}" != "${API_PORT}" ]; then
        log_info "External API port: $EXTERNAL_PORT"
    fi
    if [ "${EXTERNAL_GUI_PORT}" != "${GUI_PORT}" ]; then
        log_info "External GUI port: $EXTERNAL_GUI_PORT"
    fi
    echo ""
    
    check_prerequisites
    setup_directories
    create_default_config
    create_compose_file
    create_wrapper_script
    setup_systemd
    
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║              Installation Complete!                        ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    log_success "API Map installed to $INSTALL_DIR"
    echo ""
    echo "Quick start:"
    echo "  cd $INSTALL_DIR"
    echo "  ./apimap start"
    echo ""
    echo "Access:"
    if [ "${EXTERNAL_PORT}" != "${API_PORT}" ]; then
        echo "  API: http://localhost:$EXTERNAL_PORT (mapped to container port $API_PORT)"
    else
        echo "  API: http://localhost:$API_PORT"
    fi
    if [ "${EXTERNAL_GUI_PORT}" != "${GUI_PORT}" ]; then
        echo "  GUI: http://localhost:$EXTERNAL_GUI_PORT (mapped to container port $GUI_PORT)"
    else
        echo "  GUI: http://localhost:$GUI_PORT"
    fi
    echo ""
    echo "Configuration:"
    echo "  Edit: $CONFIG_DIR/config.yaml"
    echo "  Logs: $LOGS_DIR"
    echo ""
    
    add_to_path_suggestion
    
    echo ""
    log_info "Next steps:"
    echo "  1. Edit $CONFIG_DIR/config.yaml to add your API keys"
    echo "  2. Run: cd $INSTALL_DIR && ./apimap start"
    echo ""
}

# Run main function
main "$@"
